services:
  mysql:
    image: mysql:8.0
    container_name: mercado_livro_mysql_container
    environment:
      MYSQL_DATABASE: mercadolivro
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql